export const FETCH_CRAWL = "FETCH_CRAWL";
export const CRAWL_FAILED = "CRAWL_FAILED";
export const CRAWL_LOADING = "CRAWL_LOADING";

export const UPLOAD_CRAWL = "UPLOAD_CRAWL";
export const UPLOAD_CRAWL_FAILED = "UPLOAD_CRAWL_FAILED";
