export const FETCH_HOSPITALS = "FETCH_HOSPITALS";
export const HOSPITALS_FAILED = "HOSPITALS_FAILED";
export const HOSPITALS_LOADING = "HOSPITALS_LOADING";

export const UPLOAD_HOSPITALS = "UPLOAD_HOSPITALS";
export const UPLOAD_HOSPITALS_FAILED = "UPLOAD_HOSPITALS_FAILED";