//Login
export const LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY';
export const LOGIN_FAILED = 'LOGIN_FAILED';

//Logout
export const LOGOUT_SUCCESSFULLY = 'LOGOUT_SUCCESSFULLY';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

//Sign up
export const SIGN_UP_SUCCESSFULLY = 'SIGN_UP_SUCCESSFULLY';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const RESEND_SIGNUP_TOKEN_SUCCESSFULLY = 'RESEND_SIGNUP_TOKEN_SUCCESSFULLY';
export const RESEND_SIGNUP_TOKEN_FAILED = 'RESEND_SIGNUP_TOKEN_FAILED';

export const POST_SIGNUP_TOKEN_SUCCESSFULLY = 'POST_SIGNUP_TOKEN_SUCCESSFULLY';
export const POST_SIGNUP_TOKEN_FAILED = 'POST_SIGNUP_TOKEN_FAILED';

//Forgot/Reset password
export const GET_OTP_SUCCESSFULLY = 'GET_OTP_SUCCESSFULLY';
export const RESET_PASSWORD_SUCCESSFULLY = 'RESET_PASSWORD_SUCCESSFULLY';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

//Change password
export const CHANGE_PASSWORD_SUCCESSFULLY = 'CHANGE_PASSWORD_SUCCESSFULLY';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';

//Edit account info
export const EDIT_ACCOUNT_SUCCESSFULLY = 'EDIT_ACCOUNT_SUCCESSFULLY';
export const EDIT_ACCOUNT_FAILED = 'EDIT_ACCOUNT_FAILED';